version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE_NAME=authenticationSystem
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1h
      - PORT=3000
      - NODE_ENV=production
      - BCRYPT_SALT_ROUNDS=10
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
      - seed-users

  seed-users:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE_NAME=authenticationSystem
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_SALT_ROUNDS=10
    command: npm run seed:users
    depends_on:
      - mongo
    restart: "no"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
